### ISSUE TITLE
Missing "key" prop for element in iterator

### ISSUE THREAD

**Issue by Christian-Oleson** [keante032/SB-Capstone2#1]
Hey Kevin,

First off, good job! Way to work through a boot camp. These are hard work so you should enjoy the culmination of your efforts. I went ahead and looked at the code. I'll make a small suggestion, but I could have many more if you want me to look further. My suggestion is below, though.

The code is found here:
https://github.com/keante032/SB-Capstone2/blob/main/client/src/routes/RecipeSearch.js#L48-L60
Has a missing key prop iterator for the elements. React expects you to put a unique identifier via a key in any list of components, as this optimizes rendering. Without this, large lists negatively impact performance and can cause excessive renders in the Shadow Dom. Instead, I would suggest you add a key to the column like this:
```
                            <Col key={`col-${recipe.id}`}>
                                <Card key={recipe.id} className="h-100">
                                    <Card.Img variant="top" src={recipe.imageUrl} style={{height: "200px", "object-fit": "cover"}} />
                                    <Card.Body>
                                        <Card.Title>{recipe.name}</Card.Title>
                                        <Card.Text>by {recipe.ownerName}</Card.Text>
                                        <Card.Text>{recipe.description}</Card.Text>
                                    </Card.Body>
                                    <LinkContainer to={`/recipes/${recipe.id}`}>
                                        <Button variant="primary">View Recipe</Button>
                                    </LinkContainer>
                                </Card>
                            </Col>
```

**Comment by keante032** [comment]
Thanks for submitting this issue, Christian!

This same issue also exists in routes/PublicRecipes.js and routes/Dashboard.js. I'm committing the fix to all three now.
